@url_api = http://localhost:8000
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2FybmFtZSI6IkFkbWluaXN0cmFkb3IiLCJwcm9maWxlIjoiYWRtaW4iLCJpZCI6MSwiaWF0IjoxNzI2NzUxODE0LCJleHAiOjE3MjY3NTI3MTR9.qS4Y3gm0fIjtkPxpQgBgMeC27EGOEzaMRCQa8f0Au4o



### OTRO
POST {{url_api}}/api/search
Content-Type: application/json

{
    "query_datetime": "2024-10-01 14:00:00"
}

### LOGIN
POST {{url_api}}/api/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password" : "P@ssw0rd"
}


### QUERY
POST {{url_api}}/search
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "query_datetime": "2024-09-23 19:00"
}